name: 构建和部署

on:
  push:
    branches: [ main ]  # 根据你的主分支名称调整，可能是master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v4

      # 设置Node.js环境
      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 安装依赖
      - name: 安装依赖
        run: npm ci

      # 构建项目
      - name: 构建
        run: npm run build

      # 安装sshpass工具
      - name: 安装sshpass
        run: sudo apt-get install -y sshpass

      # 部署到服务器
      - name: 部署到服务器
        env:
          SERVER_IP: 139.224.59.6
          SERVER_USER: root
          SERVER_PASS: ${{ secrets.SERVER_PASSWORD }}
          SERVER_PATH: /www/wwwroot/tyle.hxxd.tv
        run: |
          # 压缩dist目录
          tar -czvf dist.tar.gz dist/
          
          # 使用sshpass和scp上传文件
          sshpass -p "$SERVER_PASS" scp -o StrictHostKeyChecking=no dist.tar.gz $SERVER_USER@$SERVER_IP:$SERVER_PATH/
          
          # 解压文件并设置权限
          sshpass -p "$SERVER_PASS" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd $SERVER_PATH && rm -rf dist && tar -xzvf dist.tar.gz && chmod -R 755 dist && rm dist.tar.gz"
